### ISSUE TITLE
Enable text compression on text (HTML, CSS, JS) files

### ISSUE THREAD

**Issue by fydar** [fydar/fydar.dev#22]
Using ASP.NET Core's middleware pipeline, add middleware that will compress the response returned to the client to reduce page load times.

URL | Transfer Size | Potential Savings
-- | -- | --
https://anthonymarmont.com | 73.4 KiB | 57.3 KiB
/css/main.css | 24.8 KiB | 19.8 KiB

**Comment by Fydar** [comment]
This should probably be implemented
